GENERALIZED_KENDALL_TAU_DISTANCE = 1
GENERALIZED_INDUCED_KENDALL_TAU_DISTANCE = 2
PSEUDO_METRIC_BASED_ON_GENERALIZED_INDUCED_KENDALL_TAU_DISTANCE = 3


def as_tuple_list():
    return (
        (
            GENERALIZED_KENDALL_TAU_DISTANCE,
            "GENERALIZED_KENDALL_TAU_DISTANCE"
        ),
        (
            GENERALIZED_INDUCED_KENDALL_TAU_DISTANCE,
            "GENERALIZED_INDUCED_KENDALL_TAU_DISTANCE"
        ),
        (
            PSEUDO_METRIC_BASED_ON_GENERALIZED_INDUCED_KENDALL_TAU_DISTANCE,
            "PSEUDO_METRIC_BASED_ON_GENERALIZED_INDUCED_KENDALL_TAU_DISTANCE"
        ),
    )
