# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0002_create_default_distances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
