# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0003_auto_20171128_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='distance_used',
        ),
        migrations.RemoveField(
            model_name='job',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='result',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='result',
            name='job',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
