# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0007_auto_20171209_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='distance_used',
        ),
        migrations.RemoveField(
            model_name='job',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='result',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='result',
            name='job',
        ),
        migrations.DeleteModel(
            name='DataSet',
        ),
        migrations.DeleteModel(
            name='Distance',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
