# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 23:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64, unique=True)),
                ('content', models.TextField()),
                ('m', models.IntegerField(help_text='The number of rankings')),
                ('n', models.IntegerField(help_text='The number of elements')),
                ('complete', models.BooleanField(help_text='Are every elements present in each rankings of the dataset')),
                ('step', models.IntegerField(blank=True, help_text='The number of steps used to generate the dataset, if pertinent', null=True)),
                ('transient', models.BooleanField(help_text='Should be deleted when the associated job is removed')),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(help_text='Creation time')),
                ('distance_used', models.ForeignKey(help_text='The distance used for this job', on_delete=django.db.models.deletion.CASCADE, to='mediane.Distance')),
                ('owner', models.ForeignKey(help_text='User who created this job', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_value', models.FloatField(blank=True, null=True)),
                ('results', models.TextField(blank=True, help_text="the consensus(es) computed for the givent dataset and job's distance", null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediane.DataSet')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediane.Job')),
            ],
        ),
    ]
