# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediane', '0007_create_distances_20171221_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='key_name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='distance',
            name='name',
            field=models.CharField(max_length=224, unique=True),
        ),
    ]
