# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 04:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediane', '0008_auto_20171221_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distance',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='distance',
            name='name',
        ),
    ]
