# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediane', '0004_auto_20171220_1729'),
        ('mediane', '0009_auto_20171221_0427'),
    ]

    operations = [
    ]
