# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 15:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mediane.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mediane', '0010_merge_20171221_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(max_length=32, unique=True)),
                ('key_name_is_read_only', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='dataset',
            name='content',
            field=models.TextField(validators=[mediane.validators.sound_dataset_validator]),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='owner',
            field=models.ForeignKey(help_text='The user who can see, edit and delete it', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
