# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 12:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mediane', '0015_job_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='owner',
            field=models.ForeignKey(default=1, help_text='The user who can see, edit and delete it', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distance',
            name='scoring_scheme_str',
            field=models.TextField(blank=True, help_text='The scoring scheme in a json compatible format', null=True, verbose_name='scoring_scheme'),
        ),
    ]
