# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediane', '0016_auto_20180123_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='is_scoring_scheme_relevant',
            field=models.BooleanField(default=True, help_text='Doas looking at the scoring scheme have a meaning ?', verbose_name='is_scoring_scheme_relevant'),
        ),
    ]
