# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediane', '0018_providing_scoring_scheme_20180201_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='is_scoring_scheme_relevant',
            field=models.BooleanField(default=False, help_text='Does looking at the scoring scheme have a meaning ?', verbose_name='is_scoring_scheme_relevant'),
        ),
    ]
