# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediane', '0022_auto_20180215_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='consensuses',
            field=models.TextField(blank=True, help_text="the consensus(es) computed for the given dataset and job's distance", null=True),
        ),
    ]
