# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import rest_framework.compat


class Migration(migrations.Migration):

    dependencies = [
        ('mediane', '0025_job_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='identifier',
            field=models.CharField(max_length=32, validators=[rest_framework.compat.MinLengthValidator(32)]),
        ),
    ]
