# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediane', '0026_auto_20180216_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalization',
            name='id_order',
            field=models.IntegerField(default=0),
        ),
    ]
