# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediane', '0028_algorithm_id_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='task_count',
            field=models.IntegerField(default=0, help_text='Number of results associated to it', verbose_name='task_count'),
        ),
    ]
