# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediane', '0029_job_task_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (4, 'Done'), (5, 'Error'), (6, 'Canceled')], default=1),
        ),
    ]
