# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediane', '0030_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='duration',
            field=models.FloatField(blank=True, help_text='the duration expressed in ms', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Running'), (4, 'Done'), (5, 'Error'), (6, 'Canceled')], default=1),
        ),
    ]
