# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediane', '0031_auto_20180221_0846'),
        ('mediane', '0031_auto_20180221_2052'),
    ]

    operations = [
    ]
