# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediane', '0032_merge_20180221_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='m',
            field=models.IntegerField(default=0, help_text='The number of rankings'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='n',
            field=models.IntegerField(default=0, help_text='The number of elements'),
        ),
    ]
