# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediane', '0033_auto_20180221_2222'),
        ('mediane', '0032_auto_20180222_2119'),
    ]

    operations = [
    ]
