# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediane', '0034_merge_20180224_2144'),
        ('mediane', '0034_merge_20180225_2312'),
    ]

    operations = [
    ]
