# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediane', '0035_auto_20180301_1140'),
        ('mediane', '0036_auto_20180225_2325'),
    ]

    operations = [
    ]
