# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-12 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediane', '0037_merge_20180302_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='can_be_executed',
            field=models.BooleanField(default=True, help_text='Is the algorithm can be executed on this computer'),
        ),
    ]
