# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediane', '0037_merge_20180302_0955'),
        ('mediane', '0037_merge_20180302_1213'),
    ]

    operations = [
    ]
