# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediane', '0038_algorithm_can_be_executed'),
        ('mediane', '0038_merge_20180302_1317'),
    ]

    operations = [
    ]
