# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-06 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediane', '0038_algorithm_can_be_executed'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='in_db_desc',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='distance',
            name='in_db_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='name'),
        ),
    ]
