# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-07 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediane', '0039_auto_20180406_1345'),
        ('mediane', '0039_merge_20180314_0854'),
    ]

    operations = [
    ]
